apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-container
          image: sohilametwaly/notification-service
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: NODE_ENV
              value: "development"
            - name: FRONTEND_URL
              value: "http://localhost:5173"
            - name: MAIL_USER
              value: "bashar.eg6645@gmail.com"
            - name: MAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: MAIL_APP_PASSWORD
