apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction-container
          image: sohilametwaly/transaction-service
          ports:
            - containerPort: 5002
              name: http
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: transaction-service-secrets
                  key: MONGODB_URL
