apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secrets
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9zb2hhaWxhcmFmYXQzMzA6VXp1bWc0bkt5RVk3cWFIRkBjbHVzdGVyMC51aGVrdmFhLm1vbmdvZGIubmV0L3RyYW5zYWN0aW9ucz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
